name: Build and Deploy

on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.BUILD_DEPLOY }}
        TARGET_REPO: vitdocjs/vitdocjs.github.io
        TARGET_BRANCH: _dist
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vitepress/dist
#         CNAME: https://www.xxx.com
